// ECC values from ETSI TS 101 756 Table 3
// GCC (Global Country Code) = ECC (2 hex digits) + country nibble (1 hex digit)
// The country nibble is the first hex digit of EId (for DAB) or PI code (for FM).
// Example: UK ECC=ce, EId=1066 → country nibble=1 → GCC=ce1
//          UK ECC=ce, PI=c204  → country nibble=c → GCC=cec
export const ECC_BY_COUNTRY: Array<{ country: string; ecc: string }> = [
  { country: 'Albania', ecc: 'e8' },
  { country: 'Algeria', ecc: 'e1' },
  { country: 'Andorra', ecc: 'e2' },
  { country: 'Austria', ecc: 'e9' },
  { country: 'Azores', ecc: 'e5' },
  { country: 'Belarus', ecc: 'f2' },
  { country: 'Belgium', ecc: 'e5' },
  { country: 'Bosnia-Herzegovina', ecc: 'f1' },
  { country: 'Bulgaria', ecc: 'f2' },
  { country: 'Croatia', ecc: 'f1' },
  { country: 'Cyprus', ecc: 'e2' },
  { country: 'Czech Republic', ecc: 'e2' },
  { country: 'Denmark', ecc: 'e3' },
  { country: 'Egypt', ecc: 'e6' },
  { country: 'Estonia', ecc: 'f5' },
  { country: 'Faroe Islands', ecc: 'f3' },
  { country: 'Finland', ecc: 'e4' },
  { country: 'France', ecc: 'e8' },
  { country: 'Germany', ecc: 'e0' },
  { country: 'Gibraltar', ecc: 'ee' },
  { country: 'Greece', ecc: 'e1' },
  { country: 'Hungary', ecc: 'ea' },
  { country: 'Iceland', ecc: 'f5' },
  { country: 'Iraq', ecc: 'f6' },
  { country: 'Ireland', ecc: 'e4' },
  { country: 'Israel', ecc: 'e3' },
  { country: 'Italy', ecc: 'e4' },
  { country: 'Jordan', ecc: 'f6' },
  { country: 'Kosovo', ecc: 'f1' },
  { country: 'Latvia', ecc: 'f5' },
  { country: 'Lebanon', ecc: 'f6' },
  { country: 'Libya', ecc: 'f4' },
  { country: 'Lithuania', ecc: 'f5' },
  { country: 'Luxembourg', ecc: 'e5' },
  { country: 'Macedonia', ecc: 'f1' },
  { country: 'Malta', ecc: 'eb' },
  { country: 'Moldova', ecc: 'f2' },
  { country: 'Monaco', ecc: 'ee' },
  { country: 'Montenegro', ecc: 'f1' },
  { country: 'Morocco', ecc: 'e7' },
  { country: 'Netherlands', ecc: 'e3' },
  { country: 'Norway', ecc: 'ee' },
  { country: 'Palestine', ecc: 'e7' },
  { country: 'Poland', ecc: 'e3' },
  { country: 'Portugal', ecc: 'e5' },
  { country: 'Romania', ecc: 'f2' },
  { country: 'Russia', ecc: 'e6' },
  { country: 'San Marino', ecc: 'e4' },
  { country: 'Saudi Arabia', ecc: 'f7' },
  { country: 'Serbia', ecc: 'f1' },
  { country: 'Slovakia', ecc: 'f2' },
  { country: 'Slovenia', ecc: 'f1' },
  { country: 'Spain', ecc: 'ee' },
  { country: 'Sweden', ecc: 'ee' },
  { country: 'Switzerland', ecc: 'ee' },
  { country: 'Syria', ecc: 'f6' },
  { country: 'Tunisia', ecc: 'e7' },
  { country: 'Turkey', ecc: 'f3' },
  { country: 'Ukraine', ecc: 'f2' },
  { country: 'United Kingdom', ecc: 'ce' },
  { country: 'Vatican', ecc: 'e4' },
];
