// ECC values from ETSI TS 101 756 V2.5.1, Tables 3–7
// GCC (Global Country Code) = country nibble (1 hex digit) + ECC (2 hex digits)
// The country nibble is the first hex digit of EId (for DAB) or PI code (for FM).
// Example: UK ECC=e1, EId=c188 → country nibble=c → GCC=ce1
//          UK ECC=e1, PI=c204  → country nibble=c → GCC=ce1
export const ECC_BY_COUNTRY: Array<{ country: string; ecc: string }> = [
  // Europe (ITU Region 1, Table 3)
  { country: 'Albania', ecc: 'e0' },
  { country: 'Andorra', ecc: 'e0' },
  { country: 'Armenia', ecc: 'e4' },
  { country: 'Austria', ecc: 'e0' },
  { country: 'Azerbaijan', ecc: 'e3' },
  { country: 'Azores', ecc: 'e4' },
  { country: 'Belarus', ecc: 'e3' },
  { country: 'Belgium', ecc: 'e0' },
  { country: 'Bosnia-Herzegovina', ecc: 'e4' },
  { country: 'Bulgaria', ecc: 'e1' },
  { country: 'Canary Islands', ecc: 'e2' },
  { country: 'Croatia', ecc: 'e3' },
  { country: 'Cyprus', ecc: 'e1' },
  { country: 'Czech Republic', ecc: 'e2' },
  { country: 'Denmark', ecc: 'e1' },
  { country: 'Estonia', ecc: 'e4' },
  { country: 'Faroe Islands', ecc: 'e1' },
  { country: 'Finland', ecc: 'e1' },
  { country: 'France', ecc: 'e1' },
  { country: 'Georgia', ecc: 'e4' },
  { country: 'Germany', ecc: 'e0' },
  { country: 'Gibraltar', ecc: 'e1' },
  { country: 'Greece', ecc: 'e1' },
  { country: 'Hungary', ecc: 'e0' },
  { country: 'Iceland', ecc: 'e2' },
  { country: 'Ireland', ecc: 'e3' },
  { country: 'Israel', ecc: 'e0' },
  { country: 'Italy', ecc: 'e0' },
  { country: 'Kazakhstan', ecc: 'e3' },
  { country: 'Kosovo', ecc: 'e4' },
  { country: 'Kyrgyzstan', ecc: 'e5' },
  { country: 'Latvia', ecc: 'e3' },
  { country: 'Liechtenstein', ecc: 'e2' },
  { country: 'Lithuania', ecc: 'e2' },
  { country: 'Luxembourg', ecc: 'e1' },
  { country: 'Madeira', ecc: 'e4' },
  { country: 'Malta', ecc: 'e0' },
  { country: 'Moldova', ecc: 'e4' },
  { country: 'Monaco', ecc: 'e2' },
  { country: 'Montenegro', ecc: 'e3' },
  { country: 'Netherlands', ecc: 'e3' },
  { country: 'North Macedonia', ecc: 'e4' },
  { country: 'Norway', ecc: 'e2' },
  { country: 'Poland', ecc: 'e2' },
  { country: 'Portugal', ecc: 'e4' },
  { country: 'Romania', ecc: 'e1' },
  { country: 'Russia', ecc: 'e0' },
  { country: 'San Marino', ecc: 'e1' },
  { country: 'Serbia', ecc: 'e2' },
  { country: 'Slovakia', ecc: 'e2' },
  { country: 'Slovenia', ecc: 'e4' },
  { country: 'Spain', ecc: 'e2' },
  { country: 'Sweden', ecc: 'e3' },
  { country: 'Switzerland', ecc: 'e1' },
  { country: 'Tajikistan', ecc: 'e3' },
  { country: 'Turkey', ecc: 'e3' },
  { country: 'Turkmenistan', ecc: 'e4' },
  { country: 'Ukraine', ecc: 'e4' },
  { country: 'United Kingdom', ecc: 'e1' },
  { country: 'Uzbekistan', ecc: 'e4' },
  { country: 'Vatican', ecc: 'e2' },
  // Arab States (ITU Region 1, Table 5)
  { country: 'Algeria', ecc: 'e0' },
  { country: 'Bahrain', ecc: 'f0' },
  { country: 'Egypt', ecc: 'e0' },
  { country: 'Iraq', ecc: 'e1' },
  { country: 'Jordan', ecc: 'e1' },
  { country: 'Kuwait', ecc: 'f2' },
  { country: 'Lebanon', ecc: 'e3' },
  { country: 'Libya', ecc: 'e1' },
  { country: 'Morocco', ecc: 'e2' },
  { country: 'Oman', ecc: 'f1' },
  { country: 'Palestine', ecc: 'e0' },
  { country: 'Qatar', ecc: 'f2' },
  { country: 'Saudi Arabia', ecc: 'f0' },
  { country: 'Syria', ecc: 'e2' },
  { country: 'Tunisia', ecc: 'e2' },
  { country: 'United Arab Emirates', ecc: 'f2' },
  { country: 'Yemen', ecc: 'f3' },
];
