import type { DocumentMeta, Service } from '../store/types';

export function generateZonefile(meta: DocumentMeta, services: Service[]): string {
  const lines: string[] = [];

  lines.push('; GENERATED BY SI-GENERATOR (https://github.com/magicbadger/si-generator)');
  lines.push('');

  if (meta.serviceProvider) {
    lines.push(`; Service Provider  : ${meta.serviceProvider}`);
  }
  if (meta.originator) {
    lines.push(`; Originator        : ${meta.originator}`);
  }
  lines.push(`; Created           : ${meta.creationTime}`);
  lines.push('');

  for (const svc of services) {
    const name =
      svc.shortNames[0]?.value || svc.mediumNames[0]?.value || 'Unknown';
    const target = svc.radiodns?.fqdn || 'placeholder.example.com';

    const records: string[] = [];

    for (const bearer of svc.bearers) {
      if (bearer.type === 'dab') {
        const m = bearer.uri.match(
          /^dab:([0-9a-f]{3})\.([0-9a-f]{4})\.([0-9a-f]{4,8})\.([0-9]+)$/i
        );
        if (m) {
          const gcc = m[1].toLowerCase();
          const eid = m[2].toLowerCase();
          const sid = m[3].toLowerCase();
          const scids = m[4];
          const ecc = gcc.slice(0, 2);

          records.push(`${`${scids}.${sid}.${eid}.${gcc}.dab`.padEnd(40)}\tIN\tCNAME\t${target}`);
          records.push(`${`${scids}.${sid}.${eid}.${ecc}.dab`.padEnd(40)}\tIN\tCNAME\t${target}`);
        }
      } else if (bearer.type === 'fm') {
        const m = bearer.uri.match(
          /^fm:([0-9a-f]{3})\.([0-9a-f]{4})\.([0-9]{5})$/i
        );
        if (m) {
          const gcc = m[1].toLowerCase();
          const pi = m[2].toLowerCase();
          const ecc = gcc.slice(0, 2);

          records.push(`${`*.${pi}.${gcc}.fm`.padEnd(40)}\tIN\tCNAME\t${target}`);
          records.push(`${`*.${pi}.${ecc}.fm`.padEnd(40)}\tIN\tCNAME\t${target}`);
        }
      }
    }

    if (records.length > 0) {
      lines.push(`; Station: ${name}`);
      lines.push(...records);
      lines.push('');
    }
  }

  return lines.join('\n');
}
